# Generated by Django 4.0.2 on 2022-03-13 04:11

from django.db import migrations, models
import django.utils.timezone
import ipfs_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=500, verbose_name='Image name')),
                ('tag', models.CharField(max_length=200, verbose_name='Image tag')),
                ('ipfs_hash', models.CharField(blank=True, default='', max_length=100, verbose_name='Hash of image in ipfs')),
                ('file_hash', models.CharField(blank=True, default='', max_length=100, verbose_name='Hash of image local')),
                ('size', models.BigIntegerField(default=0, verbose_name='Size of image')),
                ('changed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date pushed')),
                ('pin', models.BooleanField(default=False, verbose_name='Image pin status')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
            managers=[
                ('objects', ipfs_module.models.ImagesManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='images',
            constraint=models.UniqueConstraint(fields=('ipfs_hash',), name='unique_hash_value'),
        ),
    ]
