# Generated by Django 4.0.2 on 2022-04-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_id',
            field=models.CharField(default='', max_length=100, verbose_name='ID of image in docker'),
        ),
    ]
